---
- name: dependencies
  apt:
    name:
      - python-docker
      - docker-compose
- name: check installation status
  stat:
    path: "{{ nginx_le_install_dir }}/docker-compose.yml"
  register: nginx_le_preexisting_installation
- set_fact:
    nginx_le_already_installed: "{{ nginx_le_preexisting_installation.stat.exists  }}"
    nginx_le_configs_directory: "{{ nginx_le_install_dir }}/data/configs"
    nginx_le_static_directory: "{{ nginx_le_install_dir }}/data/storage/static"
- name: nginx static directory and parent dirs
  file:
    path: "{{ item }}"
    state: directory
  with_items: 
    - "{{ nginx_le_configs_directory }}"
    - "{{ nginx_le_static_directory }}"
- name: nginx dummy index file
  template:
    src: dummy_index.html
    dest: "{{ nginx_le_static_directory }}/dummy_index.html"
- name: basic nginx config
  template:
    src: catchall.conf
    dest: "{{ nginx_le_configs_directory }}/do_not_modify_or_remove.conf" 
- name: initial nginx config
  template:
    src: default.conf
    dest: "{{ nginx_le_configs_directory }}/default.conf" 
  when: not ( nginx_le_already_installed | bool )
- name: compose file
  template:
    src: docker-compose.yml
    dest: "{{ nginx_le_install_dir}}/docker-compose.yml"
- name: envfile for manual compose invocation
  template:
    src: envfile
    dest: "{{ nginx_le_install_dir}}/.env"
- name: envfile link for visibility
  file:
    state: link
    src: "{{ nginx_le_install_dir}}/.env"
    dest: "{{ nginx_le_install_dir}}/compose_project_name.env"
- include: nginx_docker_service.yml
  when: ansible_version.full is version('2.8','<') 
- include: nginx_docker_compose.yml
  when: ansible_version.full is version('2.8','>=') 
