version: "{{ nginx_le_compose_version }}"
services:
  nginx:
    image: hleb/nginx-letsencrypted:1.2.3
    restart: unless-stopped
    network_mode: host
    volumes: 
      - ./data/configs:/etc/nginx/conf.d:ro
      - ./data/storage:/mnt/data
{% for directive in nginx_le_extra_mounts %}
      - {{ directive }}
{% endfor %}
    environment:
      - AUTOFILL_DOMAINS=true
      - PRIMARY_DOMAIN={{ nginx_le_primary_domain }}
      - SSL_CERT_MODE={{ nginx_le_mode }}
      - LE_EMAIL={{ nginx_le_account }}
{% if nginx_le_logging_options_inline is defined %}
    logging: { options: { {{ nginx_le_logging_options_inline }} } }
{% endif %}
